export const modalHeader: string;
export const nameInputContainer: string;
export const input: string;
export const modalContent: string;
export const inputContainer: string;
export const modalButtons: string;
export const save: string;
export const cancel: string;
export const mainHeading: string;
