export const LOAD_ACTIVITIES = "LOAD_ACTIVITIES";
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";
export const LOAD_FIRST_ACTIVITY_IN_LEAD_PLAN = "LOAD_FIRST_ACTIVITY_IN_LEAD_PLAN";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
