export const menu: string;
export const logo: string;
export const logoSmall: string;
export const item: string;
export const rightItem: string;
export const active: string;
export const icon: string;
export const link: string;
export const currentLink: string;
