export const LOAD_LEADBOARD = "LOAD_LEADBOARD";
export const LOAD_STAGES = "LOAD_STAGES";
export const LOAD_LEADS = "LOAD_LEADS";
export const LOAD_LEAD = "LOAD_LEAD";
export const UPDATE_LEAD = "UPDATE_LEAD";
export const SET_EDIT_FUNNEL_ID = "SET_EDIT_FUNNEL_ID";
export const LOAD_ORGANIZATIONS = "LOAD_ORGANIZATIONS";

