export const LOAD_DASHBOARD = "LOAD_DASHBOARD";
export const LOAD_STAGES = "LOAD_STAGES";
export const LOAD_LEADS = "LOAD_LEADS";
export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const LOAD_LEAD = "LOAD_LEAD";
export const UPDATE_LEAD = "UPDATE_LEAD";
export const LOAD_ORGANIZATIONS = "LOAD_ORGANIZATIONS";
export const LEAD_NOT_FOUND = "LEAD_NOT_FOUND";
export const SET_ACTIVE_FUNNEL = "SET_ACTIVE_FUNNEL";
export const LOAD_FUNNELS = "LOAD_FUNNELS";
export const DASHBOARD_LOADING = "DASHBOARD_LOADING";
export const SET_DASHBOARD_FUNNELS_FILTER = "SET_DASHBOARD_FUNNELS_FILTER";
export const SET_ACTIVE_FILTER = "SET_ACTIVE_FILTER";
export const ADD_DASHBOARD_FUNNELS_FILTER = "ADD_DASHBOARD_FUNNELS_FILTER";

