export const GET_ORGANIZATIONS_DATA = 'GET_ORGANIZATIONS_DATA';
export const GET_CONTACTS_DATA = 'GET_CONTACTS_DATA';
export const GET_CONTACT_FIELDS = 'GET_CONTACT_FIELDS';
export const GET_ORGANIZATION_FIELDS = 'GET_ORGANIZATION_FIELDS';
